const DAYS=['월','화','수','목','금','토','일'];
const COLORS=['#dbeafe','#dcfce7','#fef3c7','#fce7f3','#ede9fe','#cffafe','#ffedd5','#e0e7ff','#fae8ff','#d1fae5'];
const roomRe=/(.+?)-([A-Za-z]?\d+(?:-\d+)?)(?=\s+(?:.+?)-[A-Za-z]?\d+(?:-\d+)?(?:\s|$)|$)/g;
function roomsOf(s){const a=[]; roomRe.lastIndex=0; let m; while((m=roomRe.exec(String(s||'').trim())))a.push({building:m[1].trim(),room:m[2].trim(),full:`${m[1].trim()}-${m[2].trim()}`}); return a}
function timesOf(s){const out=[]; const re=/([월화수목금토일])\(([^)]*)\)/g; let m; while((m=re.exec(String(s||'')))){const ranges=[]; for(const p of m[2].split(',')){const nums=p.match(/\d+/g); if(!nums)continue; let a=+nums[0],b=+(nums[1]??nums[0]); if(b<a)[a,b]=[b,a]; ranges.push({start:a,end:b,raw:p.trim()})} if(ranges.length)out.push({day:m[1],ranges})} return out}
function expand(rows){const out=[]; for(const r of rows){const rs=roomsOf(r.BLDG_COUM),ts=timesOf(r.LSTM_LIST); if(!rs.length||!ts.length)continue; ts.forEach((t,i)=>{const targets=rs.length===ts.length?[rs[i]]:rs.length===1?rs:rs; for(const rm of targets)for(const q of t.ranges)out.push({...rm,day:t.day,start:q.start,end:q.end,subject:r.SUBJ_KNM||r.SUBJ_CD_NM||'과목명 없음',lect:r.LECT_NUMB||'',prof:r.PROF_NM||'',subj:r.SUBJ_CD||''})})}
 const seen=new Set(); return out.filter(x=>{const k=[x.full,x.day,x.start,x.end,x.subject,x.lect,x.prof].join('|');if(seen.has(k))return false;seen.add(k);return true})}
const S=expand(window.SEOULTECH_RAW.rows||[]), bSel=document.querySelector('#building'),rSel=document.querySelector('#room'),tt=document.querySelector('#timetable'),summary=document.querySelector('#summary');
const nat=(a,b)=>a.localeCompare(b,'ko',{numeric:true});
function fillBuildings(){const bs=[...new Set(S.map(x=>x.building))].sort(nat);bSel.innerHTML='<option value="" selected>건물을 선택하세요</option>'+bs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');fillRooms()}
function fillRooms(){if(!bSel.value){rSel.innerHTML='<option value="" selected>강의실을 선택하세요</option>';rSel.disabled=true;render();return;} const rs=[...new Set(S.filter(x=>x.building===bSel.value).map(x=>x.room))].sort(nat);rSel.disabled=false;rSel.innerHTML='<option value="" selected>강의실을 선택하세요</option>'+rs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');render()}
function hash(s){let h=0;for(const c of s)h=(h*31+c.charCodeAt(0))>>>0;return h}
function render(){tt.innerHTML=''; const blank=document.createElement('div');blank.className='cell head';tt.append(blank);DAYS.forEach((d,i)=>{const e=document.createElement('div');e.className='cell head';e.textContent=d;e.style.gridColumn=i+2;e.style.gridRow=1;tt.append(e)});for(let p=0;p<=14;p++){const e=document.createElement('div');e.className='cell period';e.textContent=`${p}교시`;e.style.gridColumn=1;e.style.gridRow=p+2;tt.append(e);for(let d=0;d<7;d++){const c=document.createElement('div');c.className='cell';c.style.gridColumn=d+2;c.style.gridRow=p+2;tt.append(c)}}
 if(!bSel.value||!rSel.value){summary.textContent=!bSel.value?'건물을 선택하세요.':'강의실을 선택하세요.';return;} const list=S.filter(x=>x.building===bSel.value&&x.room===rSel.value); for(const x of list){const e=document.createElement('div');e.className='course';e.style.background=COLORS[hash(x.subject+x.lect)%COLORS.length];e.style.gridColumn=DAYS.indexOf(x.day)+2;e.style.gridRow=`${x.start+2} / ${x.end+3}`;e.innerHTML=`${esc(x.subject)}${x.lect?`<small>${esc(x.lect)}분반</small>`:''}`;tt.append(e)} summary.textContent=`${bSel.value} ${rSel.value} · 등록된 수업 ${list.length}개`;}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
bSel.addEventListener('change',fillRooms);rSel.addEventListener('change',render);fillBuildings();
